name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AzureConnection: ${{ secrets.AZURE_CONNECTION }}
      SubscriptionName: 'Azure subscription 1'
      location: 'East US'
      resourceGroupName: 'RG01'
      environment: 'dev'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Resource Group
      if: ${{ github.event.inputs.deployrg == 'true' }}
      run: |
        az deployment sub create \
          --name deployResourceGroup \
          --location ${{ env.location }} \
          --template-file bicepRoot/main.bicep \
          --parameters @bicepParam/parameters.${{ env.environment }}.bicepparam \
          --parameters deployadf=${{ github.event.inputs.deployadf }} deployrg=${{ github.event.inputs.deployrg }}

    - name: Deploy Data Factory
      if: ${{ github.event.inputs.deployadf == 'true' || github.event.inputs.deploylaw == 'true' }}
      run: |
        az deployment group create \
          --name deployDataFactory \
          --resource-group ${{ env.resourceGroupName }} \
          --template-file bicepRoot/main.bicep \
          --parameters @bicepParam/parameters.${{ env.environment }}.bicepparam \
          --parameters deployadf=${{ github.event.inputs.deployadf }} deployrg=${{ github.event.inputs.deployrg }} deploylaw=${{ github.event.inputs.deploylaw }}
