name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - uat
          - preprod
          - prod
      deployrg:
        description: 'Deploy Resource Group'
        required: true
        default: false
        type: boolean
      deployadf:
        description: 'Deploy Data Factory Instance'
        required: true
        default: false
        type: boolean
      deploylaw:
        description: 'Deploy Log Analytics Workspace'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AzureConnection: ${{ secrets.AZURE_CONNECTION }}
      SubscriptionName: 'Azure subscription 1'
      location: 'East US'
      resourceGroupName: 'RG01'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Resource Group
      if: ${{ github.event.inputs.deployrg }}
      run: |
        az deployment sub create \
          --name deployResourceGroup \
          --location ${{ env.location }} \
          --template-file bicepRoot/main.bicep \
          --parameters @bicepParam/parameters.${{ github.event.inputs.environment }}.bicepparam \
          --parameters deployadf=${{ github.event.inputs.deployadf }} deployrg=${{ github.event.inputs.deployrg }}

    - name: Deploy Data Factory
      if: ${{ github.event.inputs.deployadf || github.event.inputs.deploylaw }}
      run: |
        az deployment group create \
          --name deployDataFactory \
          --resource-group ${{ env.resourceGroupName }} \
          --template-file bicepRoot/main.bicep \
          --parameters @bicepParam/parameters.${{ github.event.inputs.environment }}.bicepparam \
          --parameters deployadf=${{ github.event.inputs.deployadf }} deployrg=${{ github.event.inputs.deployrg }} deploylaw=${{ github.event.inputs.deploylaw }}
